### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by dheerajvs** [CoenraadS/Bracket-Pair-Colorizer-2#331] opened 2020-08-28 12:56 UTC
- Issue Type: `Bug`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.2.0`
- OS Version: `Darwin x64 19.5.0`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 222,
		"activateCallTime": 383,
		"activateResolvedTime": 829,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "CoenraadS.bracket-pair-colorizer-2",
				"_lower": "coenraads.bracket-pair-colorizer-2"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		},
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		},
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'getRuleStack' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'getRuleStack' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'getRuleStack' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'getRuleStack' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'getRuleStack' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'getRuleStack' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'getRuleStack' of undefined"
		}
	]
}
```

**Comment by docwhat** [comment] 2021-02-02 03:19
I'm pretty sure this is a duplicate of #295

**Comment by aravindvnair99** [comment] 2021-02-27 14:53
@dheerajvs Please close this as it's a duplicate of #295. Use that thread instead of creating a new one.

**Closed** 2021-02-28 14:42 UTC
