### ISSUE TITLE
Suddenly stopped working for Flutter / Dart

### ISSUE THREAD

**Issue by gitboss** [CoenraadS/Bracket-Pair-Colorizer-2#257] opened 2020-05-07 18:54 UTC
I was working on Flutter / Dart.

Bracket Pair Colorizer 2 (Beta) version 0.0.29

VS Code 
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

![image](https://user-images.githubusercontent.com/82304/81333453-4726c600-90c2-11ea-8ddc-804f5f342888.png)

**Comment by Davilink** [comment] 2020-05-07 21:11
Probably a duplicate of https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/249

**Comment by CoenraadS** [comment] 2020-05-08 19:44
fixed

**Closed by CoenraadS** 2020-05-08 19:44 UTC
