### ISSUE TITLE
Bug with Indent Rainbow

### ISSUE THREAD

**Issue by Sargeanthost** [CoenraadS/Bracket-Pair-Colorizer-2#317] opened 2020-07-30 19:17 UTC
Python
Highlighting Brackets does not work with Bracket Colorizer.

With Indent Rainbow:
![with](https://user-images.githubusercontent.com/36427968/88964504-556a2580-d25e-11ea-97f4-7e4d9d4b83b5.PNG)

Without Indent Rainbow (Expected behavior):
![withouth](https://user-images.githubusercontent.com/36427968/88964551-6450d800-d25e-11ea-89a9-309f5690322c.PNG)

**Comment by duskmoon314** [comment] 2020-08-04 12:13
Same problem

I opened the develop tool and saw this:

```
[[object Object]]Cannot invoke loadWASM more than once.
$onExtensionRuntimeError | @ | workbench.desktop.main.js:sourcemap:4312
-- | -- | --
  | _doInvokeHandler | @ | workbench.desktop.main.js:sourcemap:4258
  | _invokeHandler | @ | workbench.desktop.main.js:sourcemap:4258
  | _receiveRequest | @ | workbench.desktop.main.js:sourcemap:4257
  | _receiveOneMessage | @ | workbench.desktop.main.js:sourcemap:4255
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:4254
  | fire | @ | workbench.desktop.main.js:sourcemap:95
  | fire | @ | workbench.desktop.main.js:sourcemap:430
  | _receiveMessage | @ | workbench.desktop.main.js:sourcemap:435
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:432
  | fire | @ | workbench.desktop.main.js:sourcemap:95
  | acceptChunk | @ | workbench.desktop.main.js:sourcemap:428
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:427
  | t | @ | workbench.desktop.main.js:sourcemap:436
  | emit | @ | events.js:203
  | addChunk | @ | _stream_readable.js:295
  | readableAddChunk | @ | _stream_readable.js:276
  | Readable.push | @ | _stream_readable.js:210
  | onStreamRead | @ | internal/stream_base_commons.js:166

workbench.desktop.main.js:sourcemap:4312 Error: Cannot invoke loadWASM more than once.
	at Object.t.loadWASM (c:\Users\<user_name>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-oniguruma\release\main.js:1:4823)
	at TextMateLoader.loadOniguruma (c:\Users\<user_name>\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\textMateLoader.js:115:19)
	at new TextMateLoader (c:\Users\<user_name>\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\textMateLoader.js:19:31)
	at new Settings (c:\Users\<user_name>\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\settings.js:10:31)
	at new DocumentDecorationManager (c:\Users\<user_name>\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecorationManager.js:9:25)
	at restart (c:\Users\<user_name>\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\extension.js:42:37)
	at c:\Users\<user_name>\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\extension.js:7:43
	at l.fire (c:\Users\<user_name>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at s.deltaExtensions (c:\Users\<user_name>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:590:215)
	at h.$deltaExtensions (c:\Users\<user_name>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:843:824)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Maybe this can help for solve the problem.

**Comment by docwhat** [comment] 2021-02-02 03:18
Good traceback.  Duplicate of #295, though.

**Comment by aravindvnair99** [comment] 2021-02-27 14:53
@Sargeanthost Please close this as it's a duplicate of #295. Use that thread instead of creating a new one.

**Closed** 2021-02-27 16:40 UTC
