### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by thebitler** [CoenraadS/Bracket-Pair-Colorizer-2#252] opened 2020-05-01 18:58 UTC
vsc version: `1.45.0-insider`
os: `Windows 10 Corporative Insider Preview
Trial version. Build 18895.rs_prerelease.190507-2033`

![Screenshot_122](https://user-images.githubusercontent.com/45060278/80833220-61f2c980-8bee-11ea-8c54-6238de916e00.png)

**Comment by EmilianoTalamo** [comment] 2020-05-06 13:13
Same here.

Version: 1.45.0-insider
Commit: fd5d9a30259bb2bebab3e62dfd8315c2e1b27744
Date: 2020-05-04T09:21:17.770Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by Davilink** [comment] 2020-05-07 21:12
Probably a duplicate of #249

**Comment by CoenraadS** [comment] 2020-05-08 19:44
fixed

**Closed by CoenraadS** 2020-05-08 19:44 UTC

**Comment by thebitler** [comment] 2020-05-11 13:06
> fixed

thx
