### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by xaviergmail** [CoenraadS/Bracket-Pair-Colorizer-2#397] opened 2021-02-22 03:51 UTC
- Issue Type: `Bug`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.2.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.53.2`

I'm not sure if this is helpful at all but VSCode asked me to report this performance issue
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 738,
		"activateCallTime": 56,
		"activateResolvedTime": 49,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "CoenraadS.bracket-pair-colorizer-2",
				"_lower": "coenraads.bracket-pair-colorizer-2"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		}
	]
}
```

**Comment by aravindvnair99** [comment] 2021-02-27 14:56
@xaviergmail Please close this as it's a duplicate of #295. Use that thread instead of creating a new one.

**Closed** 2021-09-24 18:54 UTC
