### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by felipeplets** [CoenraadS/Bracket-Pair-Colorizer-2#85] opened 2019-03-19 17:53 UTC
- Issue Type: `Performance`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.0.28`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

[CoenraadS.bracket-pair-colorizer-2-unresponsive.cpuprofile.txt](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/files/2984807/CoenraadS.bracket-pair-colorizer-2-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by aravindvnair99** [comment] 2021-04-14 19:21
Duplicate of #55. Please close this and post there instead.

@felipeplets

**Closed** 2021-04-14 21:56 UTC
