### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by njacquemin** [CoenraadS/Bracket-Pair-Colorizer-2#222] opened 2020-03-03 18:35 UTC
- Issue Type: Performance
- Extension Name: bracket-pair-colorizer-2
- Extension Version: 0.0.29
- OS Version: Linux - Xubuntu 18.04
- VSCode version: 1.42.1

[CoenraadS.bracket-pair-colorizer-2-unresponsive.cpuprofile.txt](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/files/4282966/CoenraadS.bracket-pair-colorizer-2-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by aravindvnair99** [comment] 2021-04-14 19:07
Duplicate of #55. Please close this and post there instead.

@njacquemin

**Closed** 2021-04-15 14:01 UTC
