### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kaioduarte** [CoenraadS/Bracket-Pair-Colorizer-2#102] opened 2019-04-20 12:13 UTC
- Issue Type: `Performance`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.0.28`
- OS Version: `Linux x64 5.0.5-1-MANJARO`
- VSCode version: `1.33.1`

[CoenraadS.bracket-pair-colorizer-2-unresponsive.cpuprofile.txt](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/files/3100101/CoenraadS.bracket-pair-colorizer-2-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by aravindvnair99** [comment] 2021-04-14 19:19
Duplicate of #55. Please close this and post there instead.

@kaioduarte

**Closed** 2021-04-25 22:37 UTC
