### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by zeroidentidad** [CoenraadS/Bracket-Pair-Colorizer-2#259] opened 2020-05-07 20:15 UTC
- Issue Type: `Bug`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.0.29`
- OS Version: `Linux x64 4.15.0-99-generic`
- VSCode version: `1.45.0`

:warning: Written the needed data into your clipboard. :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8152,
		"activateCallTime": 665,
		"activateResolvedTime": 188,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "CoenraadS.bracket-pair-colorizer-2",
				"_lower": "coenraads.bracket-pair-colorizer-2"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by cmedamine** [comment] 2020-05-07 23:25
i have the same problem now!

**Comment by jordankkk** [comment] 2020-05-08 03:52
same here

**Comment by mogzol** [comment] 2020-05-08 07:18
Duplicate of #249 

I just put up a PR which should fix the issue: #260

**Comment by bajajrajesh15** [comment] 2020-05-08 08:31
Same issue updated it today morning have been facing the same issue since switched to v1 for now because is works

**Comment by CoenraadS** [comment] 2020-05-08 19:44
fixed

**Closed by CoenraadS** 2020-05-08 19:44 UTC
