### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by setyadi120** [CoenraadS/Bracket-Pair-Colorizer-2#337] opened 2020-09-20 15:08 UTC
- Issue Type: `Bug`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.2.0`
- OS Version: `Linux x64 5.4.0-47-generic`
- VSCode version: `1.48.2`
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 278,
		"activateCallTime": 147,
		"activateResolvedTime": 1110,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "CoenraadS.bracket-pair-colorizer-2",
				"_lower": "coenraads.bracket-pair-colorizer-2"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		},
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		},
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		},
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		},
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		}
	]
}
```

**Comment by docwhat** [comment] 2021-02-02 03:19
Duplicate of #295

**Comment by aravindvnair99** [comment] 2021-02-27 14:54
@setyadi120 Please close this as it's a duplicate of #295. Use that thread instead of creating a new one.

**Closed** 2021-03-07 02:00 UTC
