### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by saumyakraj** [CoenraadS/Bracket-Pair-Colorizer-2#389] opened 2021-02-10 15:01 UTC
- Issue Type: `Bug`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.2.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 69,
		"activateCallTime": 21,
		"activateResolvedTime": 10,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "CoenraadS.bracket-pair-colorizer-2",
				"_lower": "coenraads.bracket-pair-colorizer-2"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		}
	]
}
```

**Comment by aravindvnair99** [comment] 2021-02-27 14:56
@saumyakraj Please close this as it's a duplicate of #295. Use that thread instead of creating a new one.

**Closed** 2021-03-02 13:07 UTC
