### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by SmoollBrain** [CoenraadS/Bracket-Pair-Colorizer-2#375] opened 2021-01-16 14:37 UTC
- Issue Type: `Bug`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.2.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 272,
		"activateCallTime": 113,
		"activateResolvedTime": 284,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "CoenraadS.bracket-pair-colorizer-2",
				"_lower": "coenraads.bracket-pair-colorizer-2"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		},
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		}
	]
}
```

**Comment by docwhat** [comment] 2021-02-02 03:19
Duplicate of #295

**Closed** 2021-02-02 17:54 UTC
