### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fakhamatia** [CoenraadS/Bracket-Pair-Colorizer-2#113] opened 2019-05-07 20:08 UTC
- Issue Type: `Performance`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.0.28`
- OS Version: `Linux x64 4.18.0-18-generic`
- VSCode version: `1.33.1`

[CoenraadS.bracket-pair-colorizer-2-unresponsive.cpuprofile.txt](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/files/3154368/CoenraadS.bracket-pair-colorizer-2-unresponsive.cpuprofile.txt)

**Comment by aravindvnair99** [comment] 2021-04-14 19:18
Duplicate of #55. Please close this and post there instead.

@fakhamatia

**Closed** 2021-04-14 19:19 UTC
