### ISSUE TITLE
Messages 'No editors associated with document' in console

### ISSUE THREAD

**Issue by boltex** [CoenraadS/Bracket-Pair-Colorizer-2#292] opened 2020-06-16 00:31 UTC
Please include the language you are using, a screenshot, and copy/pastable example.

I'm developping an extension with its own new language, and filetype, and even its own filesystem. Dont know which of these is tripping your extension into outputting those messages. 

My extension saves and renames an open file while keeping the same editor open and focused, that s when I get your error message in the console... 

On the other hand, it doenst break the colorizing pairs and all. so thats nice.

I use the regular vscode api to save and rename so I was not expecting error messages in the console. Heres my function that does that : (this._bodyTextDocument is a vscode.TextDocument) 

```
    private _switchBody(p_newGnx: string): Thenable<boolean> {
        // * Save and rename from this.bodyUri to p_newGnx: This changes the body content & blocks 'undos' from crossing over
        if (this._bodyTextDocument) {
            return this._bodyTextDocument.save().then((p_result) => {
                const w_edit = new vscode.WorkspaceEdit();
                this._leoFileSystem.setRenameTime(p_newGnx);
                w_edit.renameFile(
                    this.bodyUri, // Old URI from last node
                    utils.strToUri(p_newGnx), // New URI from selected node
                    { overwrite: true, ignoreIfExists: true }
                );
                return vscode.workspace.applyEdit(w_edit).then(p_result => {
                    this.bodyUri = utils.strToUri(p_newGnx); // Old is now set to new to finish
                    return Promise.resolve(p_result); // Also finish by showing it if not already visible
                });
            });
        } else {
            return Promise.resolve(false);
        }
    }
```

Thanks, your plugin kicks ass btw!

**Comment by boltex** [comment] 2020-06-16 00:34
May also be because when changeing the language of an open documents triggers a 'changed' event. 

I also do this at about the same time the message popups up : 
            vscode.languages.setTextDocumentLanguage(this._bodyTextDocument, "leobody");

**Comment by IllusionMH** [comment] 2020-07-06 15:19
Looks like duplicate of #21

**Comment by CoenraadS** [comment] 2020-07-06 19:14
fixed

**Closed by CoenraadS** 2020-07-06 19:14 UTC

**Comment by boltex** [comment] 2020-07-06 19:44
Thanks! cant wait to have color in my brackets and parenthesis! I wish vscode makes you a default extension...& thanks again!

**Comment by boltex** [comment] 2020-07-06 22:45
In what commit is it fixed?
